-- 長期案：定期任務模板（MVP）
CREATE TABLE IF NOT EXISTS public."長期案任務模板" (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "專案ID" text NOT NULL,
  "任務名稱" text NOT NULL,
  "任務類型" text,
  "負責人" text,
  "備註" text,
  "每月幾號" integer NOT NULL DEFAULT 1 CHECK ("每月幾號" >= 1 AND "每月幾號" <= 31),
  "提前天數" integer NOT NULL DEFAULT 0 CHECK ("提前天數" >= 0 AND "提前天數" <= 31),
  "啟用" boolean NOT NULL DEFAULT true,
  "最後觸發鍵" text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_長期案任務模板_專案ID ON public."長期案任務模板" ("專案ID");
CREATE INDEX IF NOT EXISTS idx_長期案任務模板_啟用 ON public."長期案任務模板" ("啟用");

COMMENT ON TABLE public."長期案任務模板" IS '長期案每月固定觸發任務模板';
COMMENT ON COLUMN public."長期案任務模板"."每月幾號" IS '每月目標任務日（1~31）';
COMMENT ON COLUMN public."長期案任務模板"."提前天數" IS '在目標日前幾天建立任務';
COMMENT ON COLUMN public."長期案任務模板"."最後觸發鍵" IS '避免同月份重複建立，格式 YYYY-MM';

ALTER TABLE public."任務"
  ADD COLUMN IF NOT EXISTS "來源模板ID" bigint,
  ADD COLUMN IF NOT EXISTS "排程鍵" text;

CREATE UNIQUE INDEX IF NOT EXISTS uq_任務_模板排程鍵
  ON public."任務" ("來源模板ID", "排程鍵")
  WHERE "來源模板ID" IS NOT NULL AND "排程鍵" IS NOT NULL;

COMMENT ON COLUMN public."任務"."來源模板ID" IS '若由長期案模板建立，記錄模板ID';
COMMENT ON COLUMN public."任務"."排程鍵" IS '模板建立任務月份鍵（YYYY-MM）';
